name: Cypress Website Monitor

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run --headless

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/results
